-- liquibase formatted sql

-- changeSet Vladislav:1
create table if not exists layer(
    id int generated by default as identity primary key,
    name varchar not null,
    h_name varchar not null,
    geometry_type varchar not null,
    creation_date timestamp without time zone not null,
    description text,
    example text,
    icon_url varchar not null
);

-- rollback drop table layer;
