-- liquibase formatted sql

-- changeSet Vladislav:1

create table code(
    id int generated by default as identity primary key,
    layer_id int references layer(id) on delete cascade not null,
    code int not null,
    name varchar not null,
    description text,
    creation_date timestamp without time zone
);

-- rollback drop table code;