version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5430:5432"

  discovery:
    build: ./discovery-service/.
    ports:
      - 8070:8070

  layers_service:
      build: ./layers-service/.
      environment:
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=password
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db
        - IMAGE_STORE=
        - EUREKA_CLIENT_SERVICE-URL_defaultZone=http://discovery:8070/eureka/
      ports:
        - "8080:8080"