-- liquibase formatted sql

-- changeSet Vladislav:1
create table if not exists geocoded_file(
    id int generated by default as identity primary key,
    person_id int references person(id) on delete set null,
    creation_date timestamp without time zone not null,
    source_file varchar,
    report_file varchar,
    status varchar not null
);

-- rollback drop table item;
