spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: classifier_route
          uri: lb://classifier
          predicates:
            - Path=/classifier/**
          filters:
            - StripPrefix=1
        - id: auth_route
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: geodata_route
          uri: lb://geodata
          predicates:
            - Path=/geodata/**
          filters:
            - StripPrefix=1
        - id: search-service_route
          uri: lb://search-service
          predicates:
            - Path=/search-service/**
          filters:
            - StripPrefix=1
        - id: project-service_route
          uri: lb://project-service
          predicates:
            - Path=/project-service/**
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health, info
