spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: layer_route
          uri: lb://layers
          predicates:
            - Path=/layers/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
management:
  endpoints:
    web:
      exposure:
        include: health, info
