-- liquibase formatted sql

-- changeSet Vladislav:1
create table layer(
    id int generated by default as identity primary key,
    name varchar not null,
    h_name varchar not null,
    description varchar not null,
    icon_url varchar not null
);

-- rollback drop table layer;
