-- liquibase formatted sql

-- changeSet Vladislav:1

create table code(
    id int generated by default as identity primary key,
    layer_id int references layer(id) on delete cascade not null,
    code int not null,
    name varchar not null,
    description varchar not null
);

-- rollback drop table code;