-- liquibase formatted sql

-- changeSet Vladislav:3

create table property(
  id int generated by default as identity primary key,
  layer_id int references layer(id) on delete cascade not null,
  name varchar not null,
  h_name varchar not null,
  example varchar not null,
  data_type varchar not null
);

-- rollback drop table property;