-- liquibase formatted sql

-- changeSet Vladislav:1
create table project(
    project_id int generated by default as identity primary key,
    name varchar not null,
    comment varchar,
    created_at timestamp without time zone not null,
    modified_at timestamp without time zone not null
);

-- rollback drop table project;