-- liquibase formatted sql

-- changeSet Vladislav:2
create table message(
    message_id bigint generated by default as identity primary key,
    person_id int references person(id) on delete set null not null,
    project_id int references project(project_id) on delete cascade not null,
    content varchar not null,
    send_time timestamp without time zone
);
-- rollback drop table message;