-- liquibase formatted sql

-- changeSet Vladislav:1
create table if not exists zone(
    zone_id bigint generated by default as identity primary key,
    person_id int references person(id) on delete cascade not null,
    name varchar,
    creation_date timestamp without time zone,
    geometry geometry(Polygon, 4326)
);

-- rollback drop table zone;
