-- liquibase formatted sql

-- changeSet Vladislav:2
create table if not exists loaded_file(
    file_id int generated by default as identity primary key,
    zone_id int references zone(zone_id) on delete cascade not null,
    load_date timestamp without time zone,
    percent int default 0,
    comment varchar,
    layers varchar[],
    file_format varchar
);

-- rollback drop table loaded_file;