-- liquibase formatted sql

-- changeSet Vladislav:1
create table person(
    id int generated by default as identity primary key,
    email varchar not null,
    password varchar not null,
    phone int,
    addr varchar,
    name varchar not null,
    surname varchar not null,
    lastname varchar,
    birth_date date,
    registration_date timestamp without time zone not null,
    role varchar not null
);

-- rollback drop table person;
